/**
 * EditorialLede — the page's literary entry.
 * Generated by combining the agent's `monthStamp` + a sentence reading from
 * the customer's record (cadence-aware, no name, no surveillance language).
 * Reads like an editor's note in a magazine — drop-cap on the first paragraph.
 */

import type { RetailRegister } from '../../lib/graph-types';

interface Props {
  monthStamp?: string | null;
  register: RetailRegister;
  /** First paragraph — the agent's persona description or a derived editor's-note line */
  intro: string;
  /** Optional pull-line as italic second sentence */
  pullLine?: string | null;
}

const REGISTER_LABEL: Record<RetailRegister, string> = {
  minimal:   'A Considered Edit',
  archive:   'From the Archive',
  discovery: 'The Season at Hand',
  atelier:   "L'Atelier",
  family:    'Between Seasons',
};

export default function EditorialLede({ monthStamp, register, intro, pullLine }: Props) {
  return (
    <section className="retail-lede" data-retail-reveal="fade">
      <div className="retail-lede__label-row">
        <span className="retail-label-gold" data-retail-hairline>
          {monthStamp || 'Curated'}
        </span>
        <span className="retail-label-marquee">{REGISTER_LABEL[register]}</span>
      </div>
      <div className="retail-lede__body" data-retail-reveal>
        <p className="retail-lede__paragraph retail-dropcap">{intro}</p>
        {pullLine && (
          <p className="retail-lede__paragraph">
            <span className="retail-italic">{pullLine}</span>
          </p>
        )}
      </div>
      <span className="retail-lede__rule" />
    </section>
  );
}
